"""
Business logic shared between the server-rendered web app (app.py) and the
JSON API used by the Flutter mobile app (api.py). Keeping this here avoids
duplicating fee/attendance rules in two places.
"""
import calendar
from datetime import date, datetime, timedelta
from flask import current_app
from itsdangerous import URLSafeSerializer
from sqlalchemy import func

from models import db, Student, Attendance, Fee, DateOverride


def get_share_serializer():
    """Signs the tokens used in shareable attendance-PDF links (web and mobile API
    both use this, so a link generated by one works when opened via the other)."""
    return URLSafeSerializer(current_app.config["SECRET_KEY"], salt="attendance-share")


def previous_period_str(period):
    y, m = map(int, period.split("-"))
    m -= 1
    if m == 0:
        y -= 1
        m = 12
    return f"{y:04d}-{m:02d}"


def next_period_str(period):
    y, m = map(int, period.split("-"))
    m += 1
    if m == 13:
        y += 1
        m = 1
    return f"{y:04d}-{m:02d}"


def compute_due_and_note(student, period):
    """Base fee plus any unpaid balance from the previous month, carried forward."""
    base = student.fee_amount
    prev_period = previous_period_str(period)
    prev_fee = Fee.query.filter_by(student_id=student.id, period=prev_period).first()
    carry = 0.0
    note = None
    if prev_fee and prev_fee.status in ("pending", "partial") and prev_fee.balance() > 0:
        carry = prev_fee.balance()
        note = f"Includes Rs.{carry:.0f} carried forward from {prev_period}"
    return round(base + carry, 2), note


def generate_fees_for_period(period, due_date_obj=None):
    """Create Fee rows for every active student who doesn't already have one for
    this period, automatically carrying forward any unpaid balance from last month."""
    created = 0
    for s in Student.query.filter_by(active=True).all():
        if Fee.query.filter_by(student_id=s.id, period=period).first():
            continue
        due, note = compute_due_and_note(s, period)
        db.session.add(Fee(
            student_id=s.id, period=period, amount_due=due, amount_paid=0,
            status="pending", due_date=due_date_obj, note=note,
        ))
        created += 1
    db.session.commit()
    return created


def maybe_auto_generate_next_month():
    """Runs on every dashboard load — cheap no-op unless today is the last day of
    the month and next month's fees haven't been generated yet."""
    today = date.today()
    last_day = calendar.monthrange(today.year, today.month)[1]
    if today.day != last_day:
        return
    current_period = today.strftime("%Y-%m")
    next_period = next_period_str(current_period)
    if Fee.query.filter_by(period=next_period).first():
        return
    generate_fees_for_period(next_period)
    print(f"[auto-generate] Created fee entries for {next_period} on last day of {current_period}")


def get_dashboard_chart_data():
    """Attendance (last 14 days) + fee collection (last 6 months) chart data
    for the dashboard, computed with 2 aggregate SQL queries total instead of
    ~20 separate per-day / per-month queries. Both app.py's web dashboard and
    api.py's mobile API call this, so the two stay in sync and both get the
    speed-up. Returns the exact same values the old per-day/per-month loops
    produced — only how they're computed has changed."""
    today = date.today()

    # ---- Attendance: last 14 days, one grouped query ----
    start = today - timedelta(days=13)
    rows = (
        db.session.query(Attendance.date, Attendance.status, func.count(Attendance.id))
        .filter(Attendance.date >= start, Attendance.date <= today)
        .group_by(Attendance.date, Attendance.status)
        .all()
    )
    counts = {(d, status): cnt for d, status, cnt in rows}

    attendance_labels, attendance_present, attendance_absent = [], [], []
    for i in range(13, -1, -1):
        d = today - timedelta(days=i)
        attendance_labels.append(d.strftime("%d %b"))
        attendance_present.append(counts.get((d, "present"), 0))
        attendance_absent.append(counts.get((d, "absent"), 0))

    # ---- Fees: last 6 months, one grouped query ----
    y, m = today.year, today.month
    months = []
    for i in range(5, -1, -1):
        mm = m - i
        yy = y
        while mm <= 0:
            mm += 12
            yy -= 1
        months.append((yy, mm))
    periods = [f"{yy:04d}-{mm:02d}" for yy, mm in months]

    fee_rows = (
        db.session.query(Fee.period, func.sum(Fee.amount_due), func.sum(Fee.amount_paid))
        .filter(Fee.period.in_(periods))
        .group_by(Fee.period)
        .all()
    )
    fee_sums = {period: (due or 0, paid or 0) for period, due, paid in fee_rows}

    fee_labels, fee_due, fee_collected = [], [], []
    for yy, mm in months:
        period_str = f"{yy:04d}-{mm:02d}"
        due, paid = fee_sums.get(period_str, (0, 0))
        fee_labels.append(datetime(yy, mm, 1).strftime("%b %Y"))
        fee_due.append(due)
        fee_collected.append(paid)

    return {
        "attendance_labels": attendance_labels,
        "attendance_present": attendance_present,
        "attendance_absent": attendance_absent,
        "fee_labels": fee_labels,
        "fee_due": fee_due,
        "fee_collected": fee_collected,
    }
